repos:
  # YAML linting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint

  # Markdown formatting
  - repo: https://github.com/DavidAnson/markdownlint
    rev: v0.39.0
    hooks:
      - id: markdownlint

  # JSON formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
