---
# Production Profile Configuration
spring:
  # Database Configuration for Production (PostgreSQL)
  datasource:
    url: >
      jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:scopestack}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

# Production logging
logging:
  level:
    com.scopestack: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Security settings for production
server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
