---
spring:
  application:
    name: scopestack-product-api
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  cloud:
    vault:
      host: localhost
      port: 8200
      scheme: http
      authentication: TOKEN
      token: scopestack-dev-token
      fail-fast: false
      kv:
        enabled: true
        backend: secret
        application-name: scopestack-rest
        default-context: application
        profile-separator: '/'

server:
  port: 8443
  servlet:
    context-path: /
  ssl:
    enabled: true
    key-store: classpath:ssl/scopestack.p12
    key-store-password: scopestack123
    key-store-type: PKCS12
    key-alias: scopestack

# HTTP server for redirects (optional, for development)
server.http:
  port: 8080

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  info:
    title: ScopeStack Product Catalog API
    description: REST API for managing product catalog
    version: 1.0.0
    contact:
      name: ScopeStack Team
      email: support@scopestack.com
      url: https://scopestack.com

# Application-specific configuration
app:
  product:
    default-page-size: 20
    max-page-size: 100
    low-stock-threshold: 10
